version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "12:30"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 3
    groups:
      playwright:
        patterns:
          - "@playwright/*"
          - "playwright"
          - "playwright-core"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "12:45"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 3
